name: Actions Workflow

on:
  push:
  pull_request:
    types: [reopened, closed, opened, assigned]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -la
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          env
          echo "${{ github.token }}"
      - name: Checkout
        uses: actions/checkout@v2
      - name: List Files After Checkout
        run: |
          pwd
          ls -la
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: GS
      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time }}"

