name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello world" && whoami
      - name: temp fail step
        run: incorrect commands
      - name: multiline
        run: |
          node -v
          npm -v
          which node
          which npm
